// Generated by fastlane — https://fastlane.tools
// Do not modify manually.
import Foundation
import XCTest

var deviceLanguage = ""
var locale = ""

func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
    Snapshot.setupSnapshot(app, waitForAnimations: waitForAnimations)
}

func snapshot(_ name: String, waitForLoadingIndicator: Bool) {
    Snapshot.snapshot(name, waitForLoadingIndicator: waitForLoadingIndicator)
}

func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
    Snapshot.snapshot(name, timeWaitingForIdle: timeout)
}

enum SnapshotError: Error, CustomDebugStringConvertible {
    case cannotFindSimulatorHomeDirectory
    case cannotRunOnPhysicalDevice

    var debugDescription: String {
        switch self {
        case .cannotFindSimulatorHomeDirectory:
            return "Couldn't find simulator home directory – ensure you run on a simulator"
        case .cannotRunOnPhysicalDevice:
            return "snapshot() cannot be used on a physical device"
        }
    }
}

@objcMembers
open class Snapshot: NSObject {

    static var app: XCUIApplication?
    static var waitForAnimations = true
    static var snapshotDirectory: URL?

    open class func setupSnapshot(_ app: XCUIApplication, waitForAnimations: Bool = true) {
        Snapshot.app = app
        Snapshot.waitForAnimations = waitForAnimations
        if let dir = defaultCacheDirectory() {
            snapshotDirectory = dir
            app.launchEnvironment["FASTLANE_SNAPSHOT"]           = "YES"
            app.launchEnvironment["FASTLANE_LANGUAGE"]           = deviceLanguage
            app.launchEnvironment["FASTLANE_LOCALE"]             = locale
            app.launchEnvironment["FASTLANE_SNAPSHOT_CACHE_DIR"] = dir.absoluteString
        }
    }

    open class func snapshot(_ name: String, waitForLoadingIndicator: Bool) {
        snapshot(name, timeWaitingForIdle: waitForLoadingIndicator ? 20 : 0)
    }

    open class func snapshot(_ name: String, timeWaitingForIdle timeout: TimeInterval = 20) {
        if timeout > 0 { waitForLoadingIndicatorToDisappear(within: timeout) }
        print("snapshot: \(name)")
        sleep(1)
        guard let dir = snapshotDirectory, let sc = app?.screenshot() else { return }
        let file = dir.appendingPathComponent("\(name).png")
        try? sc.pngRepresentation.write(to: file)
    }

    class func waitForLoadingIndicatorToDisappear(within timeout: TimeInterval) {
        guard let app = app else { return }
        let deadline = Date(timeIntervalSinceNow: timeout)
        while Date() < deadline {
            if app.activityIndicators.count == 0 { return }
            usleep(200_000)
        }
    }

    class func defaultCacheDirectory() -> URL? {
        guard let home = ProcessInfo().environment["SIMULATOR_HOST_HOME"] else { return nil }
        let path = (home as NSString).appendingPathComponent("Library/Caches/tools.fastlane")
        try? FileManager.default.createDirectory(atPath: path,
                                                 withIntermediateDirectories: true,
                                                 attributes: nil)
        return URL(fileURLWithPath: path)
    }
}
